# Generated by Django 2.2.1 on 2019-05-24 09:00

from django.db import migrations, models
import django.db.models.deletion
import pos.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Karyawan',
            fields=[
                ('identity', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('tugas', models.CharField(choices=[('KASIR', 'kasir'), ('PELAYAN', 'pelayan')], max_length=8)),
            ],
            options={
                'db_table': 'Karyawan',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor', models.CharField(default=pos.models.Order.increment_invoice_number, max_length=30)),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=15)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('customer', models.CharField(max_length=30)),
                ('meja', models.CharField(max_length=3)),
                ('status', models.CharField(choices=[('AKTIF', 'aktif'), ('NONAKTIF', 'nonaktif')], max_length=10)),
                ('karyawan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Karyawan')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stok', models.CharField(choices=[('READY', 'ready'), ('NOTREADY', 'notready')], max_length=9)),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Product')),
            ],
            options={
                'db_table': 'OrderItem',
            },
        ),
    ]
