# Generated by Django 2.2.1 on 2019-05-26 08:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='karyawan',
        ),
    ]
