# Generated by Django 2.2.1 on 2019-05-19 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='karyawan',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
