# Generated by Django 2.2.1 on 2019-05-19 11:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_auto_20190519_1826'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='karyawan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pos.Karyawan'),
        ),
    ]
