# Generated by Django 2.2.1 on 2019-05-26 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0002_remove_order_karyawan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'aktif'), ('0', 'nonaktif')], max_length=10),
        ),
    ]
