# Generated by Django 2.2.1 on 2019-05-20 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0003_auto_20190519_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meja',
            field=models.IntegerField(),
        ),
    ]
