# Generated by Django 2.2.1 on 2019-05-21 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0004_auto_20190521_0508'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='meja',
            field=models.CharField(max_length=3),
        ),
    ]
