# Generated by Django 2.2.1 on 2019-05-26 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0006_auto_20190526_1759'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Karyawan',
        ),
        migrations.AddField(
            model_name='order',
            name='operator',
            field=models.CharField(default='', max_length=30),
            preserve_default=False,
        ),
    ]
