# Generated by Django 2.2.1 on 2019-06-02 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0007_auto_20190526_2359'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='qty',
            field=models.IntegerField(default=''),
            preserve_default=False,
        ),
    ]
