# Generated by Django 2.2.1 on 2019-06-02 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pos', '0009_auto_20190602_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderitem',
            name='jml',
        ),
    ]
